name = "AccurateArithmetic"
uuid = "22286c92-06ac-501d-9306-4abd417d9753"
license = "MIT"
repo = "https://github.com/JuliaMath/AccurateArithmetic.jl.git"
version = "0.3.8"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[compat]
VectorizationBase = "0.19, 0.20, 0.21"
julia = "1.5"
